#!/bin/bash

echo "Risk Documentation Hub - Document Upload Guide"
echo "============================================="
echo ""
echo "The 10 sample risk management documents have been created in:"
echo "/sample-documents/"
echo ""
echo "To upload these documents to the live site:"
echo ""
echo "1. Visit https://risk.johnnycchung.com"
echo ""
echo "2. Log in with one of these credentials:"
echo "   - Admin: admin@example.com / password123"
echo "   - Manager: manager@example.com / password123"
echo ""
echo "3. Navigate to the Documents page"
echo ""
echo "4. Click 'Upload Document' and upload each file:"
echo ""
echo "Documents to upload:"
echo "-------------------"

# List all documents with recommended categories
documents=(
  "1_Enterprise_Risk_Management_Framework.txt|Policy|HIGH"
  "2_Cybersecurity_Risk_Assessment_2025.txt|Assessment|CRITICAL"
  "3_Business_Continuity_Plan.txt|Policy|HIGH"
  "4_Financial_Risk_Policy.txt|Policy|HIGH"
  "5_Operational_Risk_Procedures.txt|Procedure|MEDIUM"
  "6_Regulatory_Compliance_Matrix.txt|Compliance|HIGH"
  "7_Third_Party_Risk_Assessment.txt|Assessment|HIGH"
  "8_Incident_Response_Plan.txt|Procedure|CRITICAL"
  "9_Data_Privacy_Impact_Assessment.txt|Assessment|HIGH"
  "10_Risk_Dashboard_Metrics_Report.txt|Report|MEDIUM"
)

echo ""
echo "File Name                                    | Category    | Risk Level"
echo "--------------------------------------------------------------------"
for doc in "${documents[@]}"; do
  IFS='|' read -r filename category risk <<< "$doc"
  printf "%-44s | %-11s | %s\n" "$filename" "$category" "$risk"
done

echo ""
echo "5. For each document, fill in:"
echo "   - Title: Use the document name (without .txt)"
echo "   - Description: Brief summary of the document"
echo "   - Category: As shown in the table above"
echo "   - Risk Level: As shown in the table above"
echo "   - Tags: Add relevant tags (e.g., 'risk', 'compliance', '2025')"
echo ""
echo "6. After uploading all documents:"
echo "   - Visit the Dashboard to see statistics"
echo "   - Use the Search page to test search functionality"
echo "   - Check the Audit page to see upload activity"
echo ""
echo "Sample documents location:"
ls -la sample-documents/*.txt
echo ""
echo "Total documents: $(ls -1 sample-documents/*.txt | wc -l)"
echo "Total size: $(du -sh sample-documents | cut -f1)"
echo ""
echo "Need help? Check DEPLOYMENT_INSTRUCTIONS.md for more details."